import { NextResponse } from 'next/server';

export async function GET(request: Request) {
    const auth = request.headers.get('authorization') || 'none';

    // ランダムな日付を生成（キャッシュ検証のため）
    const randomDate = new Date().toISOString();
    const randomNumber = Math.random();

    console.log(`[API] Request received - Auth: ${auth}, Time: ${randomDate}`);

    return NextResponse.json({
        auth,
        date: randomDate,
        random: randomNumber,
        message: 'This is a random date generated by the API.'
    });
}


export const dynamic = 'force-dynamic'