import { NextResponse } from 'next/server';

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const name = searchParams.get('name') || 'unknown';
  const auth = request.headers.get('authorization') || 'none';

  // ランダムな日付を生成（キャッシュ検証のため）
  const randomDate = new Date().toISOString();
  const randomNumber = Math.random();

  console.log(`[API] Request received - Name: ${name}, Auth: ${auth}, Time: ${randomDate}`);

  return NextResponse.json({
    name,
    auth,
    date: randomDate,
    random: randomNumber,
    message: 'This is a random date generated by the API.'
  });
}

// 動的レンダリングを強制（API自体がキャッシュされないようにする）
export const dynamic = 'force-dynamic';
